# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageCode: ko
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/ko

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en
  contentDir: content/en
  title: en title!
  params:
    description: Site description in English...
  menu:
    main:
      - name: Home
        url: /en/
        weight: 10
      - name: Resume
        url: /en/about/
        weight: 20
      - name: Library
        url: /en/library/
        weight: 30
        identifier: library
      - name: 'Library/Blog'
        url: /en/post/
        parent: library
        weight: 1
      - name: 'Library/Tutorial'
        url: /en/tutorial/
        parent: library
        weight: 2